package test;

public class MinTool {
    public static void main(String[] args) {
        String content="我不是药神\n" +
                "无双\n" +
                "动物世界\n" +
                "一出好戏\n" +
                "悲伤逆流成河\n" +
                "哈利·波特与死亡圣器(下)\n" +
                "这个杀手不太冷\n" +
                "宝贝儿\n" +
                "流浪猫鲍勃\n" +
                "霸王别姬\n" +
                "阿甘正传\n" +
                "摔跤吧！爸爸\n" +
                "盗梦空间\n" +
                "忠犬八公的故事\n" +
                "镰仓物语\n" +
                "星际穿越\n" +
                "你的名字。\n" +
                "芳华\n" +
                "让子弹飞\n" +
                "肖申克的救赎\n" +
                "泰坦尼克号\n" +
                "嗝嗝老师\n" +
                "无间道\n" +
                "楚门的世界\n" +
                "当幸福来敲门\n" +
                "血战钢锯岭\n" +
                "放牛班的春天\n" +
                "香水\n" +
                "倩女幽魂\n" +
                "飞屋环游记\n" +
                "V字仇杀队\n" +
                "初恋这件小事\n" +
                "中国合伙人\n" +
                "美丽人生\n" +
                "千与千寻\n" +
                "反贪风暴3\n" +
                "老炮儿\n" +
                "看不见的客人\n" +
                "天才枪手\n" +
                "怦然心动\n" +
                "三傻大闹宝莱坞\n" +
                "罗马假日\n" +
                "东邪西毒\n" +
                "熔炉\n" +
                "蝴蝶效应\n" +
                "嫌疑人X的献身\n" +
                "少年派的奇幻漂流\n" +
                "小偷家族\n" +
                "禁闭岛\n" +
                "猫鼠游戏\n" +
                "消失的爱人\n" +
                "海上钢琴师\n" +
                "爱乐之城\n" +
                "金陵十三钗\n" +
                "触不可及\n" +
                "敦刻尔克\n" +
                "阳光姐妹淘\n" +
                "火星救援\n" +
                "惊天魔盗团\n" +
                "失恋33天\n" +
                "蝙蝠侠：黑暗骑士\n" +
                "西西里的美丽传说\n" +
                "美丽心灵\n" +
                "无问西东\n" +
                "剪刀手爱德华\n" +
                "秒速5厘米\n" +
                "被嫌弃的松子的一生\n" +
                "三块广告牌\n" +
                "狮子王\n" +
                "喜剧之王\n" +
                "末代皇帝\n" +
                "辛德勒的名单\n" +
                "国王的演讲\n" +
                "忠犬八公物语\n" +
                "青蛇\n" +
                "指环王3：王者无敌\n" +
                "本杰明·巴顿奇事\n" +
                "辩护人\n" +
                "大追捕\n" +
                "情书\n" +
                "亲爱的\n" +
                "叶问\n" +
                "穿普拉达的女王\n" +
                "活着\n" +
                "纵横四海\n" +
                "教父\n" +
                "傲慢与偏见\n" +
                "烈日灼心\n" +
                "妖猫传\n" +
                "窃听风暴\n" +
                "一条狗的使命\n" +
                "萤火之森\n" +
                "达拉斯买家俱乐部\n" +
                "菊次郎的夏天\n" +
                "搏击俱乐部\n" +
                "窃听风云\n" +
                "拯救大兵瑞恩\n" +
                "荒蛮故事\n" +
                "请以你的名字呼唤我\n" +
                "神奇动物在哪里\n" +
                "七宗罪\n" +
                "影\n" +
                "恐怖直播\n";

        String result=content.replace("\n", "\",\"");
        String url="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2519070834.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535096871.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2525528688.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2529571873.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2529701498.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p917846733.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p511118051.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2531326284.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535524955.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910813120.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p510876377.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2457983084.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p513344864.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p524964016.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2532008868.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2206088801.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2395733377.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2507227732.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1512562287.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p480747492.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p457760035.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535365481.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2233971046.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p479682972.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1312700744.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2398141939.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910824951.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p470006658.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2414157745.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2364094053.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1465235231.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1505312273.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1959304567.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p510861873.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1606727862.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2531887203.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2292976849.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2498971355.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2501863104.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p663036666.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p579729551.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2189265085.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1982176012.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1363250216.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2209066019.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2448676053.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1784592701.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2530599636.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1832875827.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p453924541.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2221768894.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p511146807.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2425658570.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1322247572.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1454261925.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2494950714.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1374786017.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2280097442.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2151336415.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1252876266.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p462657443.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p792400696.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1665997400.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2507572275.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p480956937.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p982896012.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p453723669.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2510081688.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p726659067.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1043597424.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p452088641.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p492406163.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p768879237.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2297934945.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p584021784.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910825503.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2192535722.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2158166535.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1451250805.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p449897379.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2199507156.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p458263441.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p735379215.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2513253791.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2272146906.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2190556185.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p452005185.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2262236348.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2530249558.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1808872109.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2432493858.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1272904657.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2166160837.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p751835224.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1910926158.jpg\n" +
                "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1839391107.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1014542496.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2192834364.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2505525050.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2392444121.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p457631605.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2530513100.jpg\n" +
                "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2016930906.jpg\n";
        String resultUrl=url.replace("\n", "\",\"");
        System.out.println("-------------------"+resultUrl);
    }
}
